### ISSUE TITLE
Jenkins docker client too old

### ISSUE THREAD

**Issue by Algirdas-Z** [hostinger/hbl#54]
On recent docker build change, image can't be pushed:
```
09:14:25  + /bin/docker push eu.gcr.io/hostinger-systems/hostinger-hbl --all-tags
09:14:25  unknown flag: --all-tags
09:14:25  See 'docker push --help'.
```

Who wants to investigate how to upgrade docker client on jenkins slaves?
@auktuma-sadauskas @konradasb

**Comment by auktuma-sadauskas** [comment]
Ran `yum upgrade docker-ce docker-ce-cli containerd.io`, issue resolved.
